#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    guifont = "Iosevka Nerd Font Mono:h13"
    guifontwide = "Glow Sans SC Normal:h13"
    default_indent = 4
    autocomplete_method = "coc"
    filemanager = "nerdtree"
    bootstrap_before = "myspacevim#init"

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "lang#julia"

[[layers]]
  name = "lang#toml"

[[layers]]
  name = "lang#python"
  format_on_save = 1
  enable_typeinfo = true

[[layers]]
  name = "lang#latex"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "git"

[[layers]]
    name = 'core'
    filetree_show_hidden = true

[[custom_plugins]]
    repo = "ryanoasis/vim-devicons"
    merged = false

[[custom_plugins]]
    repo = "tiagofumo/vim-nerdtree-syntax-highlight"
    merged = false

[[layers]]
name = "ctrlp"

[[custom_plugins]]
    repo = "jaxbot/semantic-highlight.vim"
    merged = false

[[layers]]
name = "tools#dash"
